import { defineConfig } from '@kubb/core';
import { pluginOas } from '@kubb/plugin-oas';
import { pluginReactQuery } from '@kubb/plugin-react-query';
import { pluginTs } from '@kubb/plugin-ts';
import { pluginZod } from '@kubb/plugin-zod';

/**
 * kubb configuration. Generates the typed API client (types + zod + react-query
 * hooks) from the committed backend contract (../openapi.admin.json) into
 * src/gen. The react-query hooks use our custom client (src/api/kubbClient.ts),
 * which wraps the shared auth/error behavior, and validate responses with the
 * generated zod schemas (parser: 'zod'). Run via `pnpm generate:api`.
 */
export default defineConfig({
  root: '.',
  // Source of truth: the committed admin OpenAPI spec generated by the backend (pnpm openapi).
  input: { path: '../openapi.admin.json' },
  output: {
    path: './src/gen',
    clean: true,
    barrelType: 'named',
  },
  plugins: [
    pluginOas({ validate: false }),
    pluginTs({
      output: { path: 'types' },
      enumType: 'literal',
    }),
    pluginZod({
      output: { path: 'zod' },
      typed: true,
    }),
    pluginReactQuery({
      output: { path: 'hooks' },
      client: {
        importPath: '../../api/kubbClient',
        dataReturnType: 'data',
      },
      parser: 'zod',
      pathParamsType: 'object',
      paramsType: 'object',
      mutation: { methods: ['post', 'put', 'patch', 'delete'] },
    }),
  ],
});
