/**
 * Invariant tests against real Postgres — counterpart of
 * src/persistence/inmemory/acceptance.repo.spec.ts. Runs only with DATABASE_URL (see
 * agreement-document.repo.prisma.spec.ts for details/invocation).
 *
 * Main purpose of this file: verify that the partial unique index from
 * prisma/partial-indexes.sql has actually been applied (it is NOT part of the migration
 * generated by `prisma migrate`, see the schema.prisma header comment) and that the P2002
 * translation in acceptance.repo.ts (`ALREADY_ACCEPTED` vs. `INVALID_STATE`) matches the real
 * DB error message — this could not be executed in this environment without Postgres.
 */
import { aCustomer, aDocument, anAcceptance, aVersion, testActor } from '../../domain/testing/fixtures';
import { PrismaAcceptanceRepo } from './acceptance.repo';
import { PrismaAgreementDocumentRepo } from './agreement-document.repo';
import { PrismaAgreementVersionRepo } from './agreement-version.repo';
import { PrismaCustomerRepo } from './customer.repo';
import { PrismaService } from './prisma.service';
import { resetDatabase } from './testing/reset-database';

const describeIfDb = process.env.DATABASE_URL ? describe : describe.skip;

describeIfDb('PrismaAcceptanceRepo (against real Postgres)', () => {
  let prisma: PrismaService;
  let repo: PrismaAcceptanceRepo;

  beforeAll(async () => {
    prisma = new PrismaService();
    await prisma.onModuleInit();
    repo = new PrismaAcceptanceRepo(prisma);
  });

  afterAll(async () => {
    await prisma.onModuleDestroy();
  });

  beforeEach(async () => {
    await resetDatabase(prisma);
    await new PrismaAgreementDocumentRepo(prisma).save(aDocument({ id: 'doc-dpa-customer' }));
    await new PrismaAgreementVersionRepo(prisma).save(aVersion({ id: 'v-1', documentId: 'doc-dpa-customer' }));
    await new PrismaAgreementVersionRepo(prisma).save(aVersion({ id: 'v-2', documentId: 'doc-dpa-customer' }));
    await new PrismaCustomerRepo(prisma).save(aCustomer({ id: 'c-123' }));
  });

  it('append + findEffective returns the effective acceptance per (customer, version)', async () => {
    await repo.append(anAcceptance({ id: 'a-1' }));
    expect((await repo.findEffective('c-123', 'v-1'))?.id).toBe('a-1');
  });

  it('partial uniqueness (partial-indexes.sql): second EFFECTIVE acceptance per (customer, version) → ALREADY_ACCEPTED', async () => {
    await repo.append(anAcceptance({ id: 'a-1' }));
    await expect(repo.append(anAcceptance({ id: 'a-2' }))).rejects.toMatchObject({
      name: 'DomainError',
      code: 'ALREADY_ACCEPTED',
    });
  });

  it('ineffective entries do not violate the uniqueness (append-only corrections, WHERE isEffective)', async () => {
    await repo.append(anAcceptance({ id: 'a-1' }));
    await expect(repo.append(anAcceptance({ id: 'a-2', isEffective: false }))).resolves.toMatchObject({ id: 'a-2' });
  });

  it('rejects a duplicate id (append-only, PK violation → INVALID_STATE)', async () => {
    await repo.append(anAcceptance({ id: 'a-1' }));
    await expect(repo.append(anAcceptance({ id: 'a-1', versionId: 'v-2' }))).rejects.toMatchObject({
      name: 'DomainError',
      code: 'INVALID_STATE',
    });
  });

  it('supersede: the old entry becomes ineffective + points to its successor; a new effective acceptance is then allowed', async () => {
    await repo.append(anAcceptance({ id: 'a-1' }));
    const superseded = await repo.supersede('a-1', 'a-2');
    expect(superseded).toMatchObject({ isEffective: false, supersededByAcceptanceId: 'a-2' });

    const replacement = await repo.append(anAcceptance({ id: 'a-2' }));
    expect(replacement.isEffective).toBe(true);
    expect(await repo.findEffective('c-123', 'v-1')).toMatchObject({ id: 'a-2' });
  });

  it('supersede on an unknown id → DomainError', async () => {
    await expect(repo.supersede('missing', 'a-2')).rejects.toMatchObject({ name: 'DomainError', code: 'INVALID_STATE' });
  });

  it('actor is mapped back completely (userId/name/email/portalRole)', async () => {
    const actor = testActor({ userId: 'u-99', name: 'Erika Example' });
    await repo.append(anAcceptance({ id: 'a-1', actor }));
    expect((await repo.findEffective('c-123', 'v-1'))?.actor).toEqual(actor);
  });

  it('findEffectiveByVersion returns only effective acceptances of the version', async () => {
    await new PrismaCustomerRepo(prisma).save(aCustomer({ id: 'c-2', externalRef: 'ext-c-2' }));
    await repo.append(anAcceptance({ id: 'a-1', customerId: 'c-123', versionId: 'v-1' }));
    await repo.append(anAcceptance({ id: 'a-2', customerId: 'c-2', versionId: 'v-1' }));
    await repo.append(anAcceptance({ id: 'a-ineff', customerId: 'c-123', versionId: 'v-1', isEffective: false }));
    await repo.append(anAcceptance({ id: 'a-other', customerId: 'c-123', versionId: 'v-2' }));

    const effective = await repo.findEffectiveByVersion('v-1');
    expect(effective.map((row) => row.id).sort()).toEqual(['a-1', 'a-2']);
  });
});
